site_name: Amazon Containers Blog Maelstrom
repo_name: "aws-samples/containers-blog-maelstrom"
repo_url: "https://github.com/aws-samples/containers-blog-maelstrom"
docs_dir: "docs"
theme:
  name: material
  features:
    - tabs
nav:
  - Overview: 'index.md'
markdown_extensions:
  - def_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
plugins:
  - search
