apiVersion: v1
kind: Service
metadata:
  namespace: sample
  name: sample-ui
  labels:
    app: sample-ui
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: sample-ui
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sample
  name: sample-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-ui
      tier: frontend
  template:
    metadata:
      labels:
        app: sample-ui
        tier: frontend
    spec:
      containers:
        - name: sample-ui
          image: 000474600478.dkr.ecr.us-east-1.amazonaws.com/sample-ui:latest
          env:
            - name: AWS_REGION
              value: "us-east-1"          
          ports:
            - containerPort: 80
---
