apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: $EDP_NAME
  region: $EDP_AWS_REGION
  version: '1.24'
#nodeGroups:
managedNodeGroups:
  - name: nodegroup
    instanceType: t3.medium
    minSize: 1
    maxSize: 3
    amiFamily: AmazonLinux2
    ssh:
      enableSsm: true
    iam:
      withAddonPolicies:
        certManager: true
        cloudWatch: true
          #preBootstrapCommands: 
          #- 'sudo systemctl start docker'
          #- 'sudo systemctl enable docker'
