apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: $EDP_NAME
  region: $EDP_AWS_REGION
  version: '1.24'
managedNodeGroups:
  - name: nodegroup
    instanceType: t3.medium
    minSize: 1
    maxSize: 3
    amiFamily: AmazonLinux2
    ssh:
      enableSsm: true
    
