apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: keda-sigv4
  name: keda-sigv4
  namespace: keda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keda-sigv4
  template:
    metadata:
      labels:
        app: keda-sigv4
      name: keda-sigv4
    spec:
      serviceAccountName: keda-operator
      containers:
      - name: aws-iamproxy
        image: public.ecr.aws/aws-observability/aws-sigv4-proxy:latest
        args:
          - --name
          - cw
          - --region
          - {{CW_AWS_REGION}}
          - --host
          - monitoring.{{CW_AWS_REGION}}.amazonaws.com
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: keda-sigv4
  namespace: keda
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: keda-sigv4
---